### ISSUE TITLE
Проклятие не снято

### ISSUE THREAD

**Issue by arsyst** [D1midr0sh/qt_poem_learner#2]
<img width="1240" alt="Screenshot 2023-10-30 at 10 38 45" src="https://github.com/D1midr0sh/qt_poem_learner/assets/74470493/37f82aea-1a5f-4ac4-add0-3cdbcf6a4469">

**Comment by D1midr0sh** [comment]
да боже я уже закончил джангу окстись

**Comment by D1midr0sh** [comment]
всё не приходи сюда больше

**Comment by arsyst** [comment]
@D1midr0sh извини) Просто хотел напомнить, что значит выложить проект в опен-сорс

**Comment by D1midr0sh** [comment]
@arsyst ничего. теперь сделаю опес-сурс только после того, как его закончу
